---
title: "GSE45458"
author: "Irzam Sarfraz"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_float: yes
    number_sections: yes
    theme: cosmo
    code_folding: show
    self_contained: true
  pdf_document: 
    toc: yes
subtitle: "Differential Expression between Replicates"
editor_options:
  chunk_output_type: console
---
# Processing
```{r, message=FALSE}
#loading required packages
library(SingleCellExperiment)
library(stringr)
library(limma)
library(GEOquery)
library(gtools)

#read expression matrix
matrix <- readRDS("./data/matrix.rds")

#make a sce object
sce <- SingleCellExperiment(list(counts = matrix))

#fetch phenotype data
gse45458 <- getGEO('GSE45458')

#get required phenotype data in dataframe
colData <- DataFrame(
  cell_type =  stringr::str_split(
    string = gse45458$GSE45458_series_matrix.txt.gz$characteristics_ch1, 
    pattern = "cell type: ", n = 2, simplify = TRUE)[, 2], 
  cytokine_treatment = stringr::str_split(
    string = gse45458$GSE45458_series_matrix.txt.gz$characteristics_ch1.1, 
    pattern = "cytokine treatment: ", n = 2, simplify = TRUE)[, 2],
  time_point = stringr::str_split(
    string = gse45458$GSE45458_series_matrix.txt.gz$characteristics_ch1.2, 
    pattern = "time point: ", n = 2, simplify = TRUE)[, 2],
  row.names = colnames(sce))

#store in colData slot of the sce object for easy manipulation
colData(sce) <- colData

# map gene ids
gene_data <- read.csv("./data/gene_data.txt", sep = "\t", header = FALSE) #V1 = transcript id, V7 = gene symbol

getGeneSymbols <- function(inputIDs){
  return(gene_data$V7[match(inputIDs, gene_data$V1)])
}
```

# ILC2_Media_24_hour (4 replicates) vs. ILC2_IL-33_24_hour (4 replicates)

```{r}
# ILC2_Media_24_hour (4 replicates) vs. ILC2_IL-33_24_hour (4 replicates)
design <- cbind("ILC2_media_24_hour" = c(rep(1, 4), rep(0, 4)), "ILC2_IL_33_24_hour" = c(rep(0,4), rep(1,4)))
rownames(design) <- c(colnames(sce)[which(sce$cytokine_treatment == "media" & sce$time_point == "24 hours")], colnames(sce)[which(sce$cytokine_treatment == "IL-33" & sce$time_point == "24 hours")])
matrix <- assay(sce, "counts")[, rownames(design)]
matrix <- na.omit(matrix)
fit <- lmFit(object = matrix, design = design)
cont.matrix <- makeContrasts(ILC2_Media_24_hour_vs_ILC2_IL_33_24_hour=ILC2_media_24_hour-ILC2_IL_33_24_hour, levels=design)
fit2 <- contrasts.fit(fit, cont.matrix)
fit2 <- eBayes(fit2)
results <- topTable(fit2, number = nrow(sce))
results$gene_symbol <- getGeneSymbols(rownames(results))
print(head(results))
write.csv(results, file = "ILC2_media_24_hour-ILC2_IL_33_24_hour.csv")
```

# All comparisons

```{r}
sce$time_point <- stringr::str_replace_all(sce$time_point, " ", "_")
allComparisons <- gtools::combinations(n = 8, r = 2, v = unique(sce$cytokine_treatment))
for(j in 1:length(unique(sce$time_point))){
  time <- unique(sce$time_point)[j]
  
  for(i in 1:nrow(allComparisons)){
    cat("\n\n")
    print(paste0(allComparisons[i, 1], " vs ", allComparisons[i, 2], " : ", time))
    
    firstComparisonIndices <- which(sce$cytokine_treatment == allComparisons[i, 1] & sce$time_point == time)
    secondComparisonIndices <- which(sce$cytokine_treatment == allComparisons[i, 2] & sce$time_point == time)
    firstComparison <- stringr::str_replace_all(allComparisons[i, 1], c("-" = "_", "," = "_", " " = ""))
    secondComparison <- stringr::str_replace_all(allComparisons[i, 2], c("-" = "_", "," = "_", " " = ""))
    
    design <- cbind(c(rep(1, length(firstComparisonIndices)), rep(0, length(secondComparisonIndices))), c(rep(0, length(firstComparisonIndices)), rep(1, length(secondComparisonIndices))))
    colnames(design) <- c(paste0(firstComparison, "_", time), paste0(secondComparison, "_", time))
    rownames(design) <- c(colnames(sce)[firstComparisonIndices], colnames(sce)[secondComparisonIndices])
    
    if(sum(design[, 1]) == 0 || sum(design[, 2]) == 0){
      print("Comparison not available, skipping to next!")
      next
    }
    
    matrix <- assay(sce, "counts")[, rownames(design)]
    matrix <- na.omit(matrix)
    fit <- lmFit(object = matrix, design = design)
    contrast <- paste0(firstComparison, "_", time, "-", secondComparison, "_", time)
    cont.matrix <- makeContrasts(contrast, levels=design)
    fit2 <- contrasts.fit(fit, cont.matrix)
    fit2 <- eBayes(fit2)
    results <- topTable(fit2, number = nrow(sce))
    results$gene_symbol <- getGeneSymbols(rownames(results))
    print(head(results))
    write.csv(results, file = paste0(firstComparison, "_", time, "-", secondComparison, "_", time, ".csv"))
  } 
}
```
